### ISSUE TITLE
node-gyp/iltorb installation issue (with solution)

### ISSUE THREAD

**Issue by dwjohnston** [rherwig/template-react-ssr#38]
If I do a fresh clone, I get this issue: 

```
sed: can't read ./Release/.deps/Release/obj.target/zopfli/src/png/zopflipng.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/zopfli/src/png/zopflipng.o.d.raw': No such file or directory
zopfli.target.mk:133: recipe for target 'Release/obj.target/zopfli/src/png/zopflipng.o' failed


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zopfli@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

If you then then do 
```
cd node_modules/node-gyp && npm i
```

Then try on root `npm i && npm start`

```
Error: Cannot find module './build/bindings/iltorb.node'
```

Now do 

```
cd node_modules/iltorb && npm i
```

then `npm i && npm start` on the root, and it should start.

**Comment by rherwig** [comment]
Which OS are you using? You need python 2.7 and node-gyp installed, plus vc build tools, if you are on windows. This is due to the library `shrink-ray` being a native lib that requires compilation

**Comment by dwjohnston** [comment]
Hmmm, I'm wondering if it's something to do with node version. WhenI swtiched from `10.13` to `9.11` it seeems to fix it.

**Comment by dwjohnston** [comment]
Can you try using node v 10.13 and see if it reproduces on your machine? (I have the same issue when building docker images too).

**Comment by rherwig** [comment]
Can reproduce with 10.13 inside a docker container. Did you try node 11 already?

**Comment by dwjohnston** [comment]
I haven't tried 11. 

For now - just insist on using 9.11?

**Comment by rherwig** [comment]
I'd love some more user feedback on this topic. I thought about excluding shrink-ray from the template, since it is not really a core req of universal apps anyways, but I'm kinda hesitant to do so... what do you think?

**Comment by rherwig** [comment]
Anyways, did you try possible gyp fixes from https://github.com/nodejs/node-gyp#option-1 ?
