### ISSUE TITLE
Render client side only?

### ISSUE THREAD

**Issue by dwjohnston** [rherwig/template-react-ssr#40]
I'm doing some stuff with websockets, and what I'm doing is that when a component mounts, it sets up all the websocket stuff. 

I'm having an issue where the server side render of that component screws up the websocket logic. Is it possible to tell a component to render on the client side only?

**Comment by dwjohnston** [comment]
Ok, this here seems to do the trick:

https://github.com/kadirahq/react-no-ssr

But any other suggestions?

**Comment by rherwig** [comment]
This is basically an abstraction of the usual approach. If the `window` object is available, you are on the client. But I like the way to wrap it inside a component.
