### ISSUE TITLE
Static cache

### ISSUE THREAD

**Issue by manish4781** [rherwig/template-react-ssr#45]
I am using this template and in top of this i have modified it to support static(browser) cache 
for 30 days and based on that after every build i am generating new has([contenthash]) for my all js file

sample code format
```
 output: {
        filename: 'app.client.js',
        chunkFilename: '[name].[contenthash].js'
    },
```
i Needed some help to understand the generation and use of **app.client.js** and is there a way i can add [contenthash] to **app.client.js** file also and where exactly this file is referred to.
https://github.com/rherwig/template-react-ssr/blob/master/webpack/client/common.js#L9

**Comment by rherwig** [comment]
For short: you could just use contenthash in the filename as well. But things easily get complicated with webpack and react... and since I see, that you are quite a regular user of this project, please hit me up, if you need a 1on1 support session. I would be glad to assist you :-)

**Comment by manish4781** [comment]
Thnaks @rherwig, thanks for the support, For now adding [hash] to every file solved my problem.
